#!/bin/sh

#echo "\nRunning Unit Tests..."
#go test -cover ./...

echo "\nExecuting gosec security test tool..."
gosec ./...

echo "\nRunning fmt styling..."
go fmt ./...

echo "\nRunning linting checks..."
staticcheck ./...
